version: '3.7'

services:

  react:
    container_name: poker_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './app:/srv/app'
      - '/srv/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
